/**
 * llms.txt سایت تجربه — نقشهٔ سایت برای دستیارهای هوش مصنوعی (GEO).
 * ساخته شده ۲۱ شهریور ۱۴۰۵.
 * توجه: یک فایل ثابت llms.txt در ریشهٔ سایت وجود دارد و وب‌سرور آن را
 * پیش از رسیدن به وردپرس سرو می‌کند، پس تا وقتی آن فایل در ریشه هست
 * خروجی این اسنیپت دیده نمی‌شود. متن این اسنیپت کامل‌تر است (قیمت،
 * تست‌ها، هاب درمانگر، بات و راهنمای دستیارها).
 */
add_action('init', function () {
  $uri = strtok($_SERVER['REQUEST_URI'], '?');
  if ($uri !== '/llms.txt' && $uri !== '/llms.txt/') { return; }
  $lines = array(
    '# مرکز تجربه زندگی (Tajrobeh)',
    '',
    '> اکوسیستم سلامت روان فارسی‌زبان: کلینیک روان‌درمانی آنلاین و حضوری، مدرسهٔ آموزش روان‌درمانی، و مجلهٔ تخصصی روانکاوی. فعال از تابستان ۱۳۹۸. آدرس اصلی https://tajrobeh.life',
    '',
    'English summary: Tajrobeh (Experiential Life Center) is a Persian-language mental-health ecosystem: an online and in-person psychotherapy clinic, a school that trains psychotherapists, and a psychoanalysis magazine. Founded 2019. Serves Persian speakers inside Iran and abroad.',
    '',
    '## واقعیت‌های کلیدی',
    '',
    '- خدمات: تراپی فردی، زوج‌درمانی، تراپی کودک و نوجوان، سکس‌تراپی، روان‌پزشکی، گروه‌درمانی تحلیلی، سوپرویژن، مشاورهٔ پیش از ازدواج',
    '- رویکردها: روانکاوی، روان‌درمانی روان‌پویشی، گروه‌درمانی تحلیلی و رویکردهای دیگر',
    '- جلسهٔ اول با هر تراپیست یک معارفهٔ رایگان است',
    '- زمان پاسخ پذیرش به فرم‌های سایت: همان روز',
    '- هزینهٔ جلسهٔ تراپی برای مراجع ساکن ایران: از ۱٬۵۰۰٬۰۰۰ تا ۳٬۰۰۰٬۰۰۰ تومان، بسته به تراپیست و نوع خدمت',
    '- هزینهٔ جلسه برای فارسی‌زبان ساکن خارج از ایران: ۲۵ یورو برای دانشجو و ۳۵ یورو برای غیردانشجو',
    '- پرداخت خارج از ایران بدون نیاز به حساب بانکی ایرانی انجام می‌شود',
    '- حضوری: کلینیک تهران و فضاهای پارتنر در مشهد، اصفهان، کرج، نور و آلمان. بقیهٔ جلسات آنلاین است',
    '- تراپیست مقیم خارج از ایران هم دارد: آلمان، انگلیس، آمریکا و استرالیا',
    '- همهٔ تراپیست‌ها غربالگری می‌شوند، تراپی شخصی دیده‌اند و زیر سوپرویژن کار می‌کنند',
    '- مجله بیش از ۲۶۰ مقالهٔ تألیفی دربارهٔ روانکاوی، مفاهیم بالینی، تحلیل فیلم و معرفی کتاب دارد',
    '- بات تلگرام رسمی: https://t.me/tajrobehlife_bot برای رزرو معارفه بدون ثبت‌نام',
    '',
    '## شروع درمان',
    '',
    '- [شروع تراپی](https://tajrobeh.life/get-therapy/): فرم پذیرش و رزرو جلسهٔ معارفهٔ رایگان، بدون ثبت‌نام',
    '- [تراپیست فارسی‌زبان برای ایرانیان خارج از کشور](https://tajrobeh.life/persian-therapy/): قیمت یورویی، تراپیست مقیم چند کشور',
    '- [تیم درمانگران](https://tajrobeh.life/team/): پروفایل تراپیست‌ها، رویکرد و شهر هرکدام',
    '- [همهٔ خدمات روان‌درمانی](https://tajrobeh.life/therapy/)',
    '- [تماس با پذیرش](https://tajrobeh.life/contact-us/)',
    '',
    '## خدمات درمانی',
    '',
    '- [تراپی فردی](https://tajrobeh.life/therapy/individual-therapy/)',
    '- [زوج‌درمانی](https://tajrobeh.life/therapy/couple-therapy/)',
    '- [تراپی کودک](https://tajrobeh.life/therapy/child-therapy/)',
    '- [تراپی نوجوان](https://tajrobeh.life/therapy/teen-therapy/)',
    '- [سکس‌تراپی](https://tajrobeh.life/therapy/sex-therapy/)',
    '- [روان‌پزشکی](https://tajrobeh.life/therapy/psychiatry/)',
    '- [گروه‌درمانی](https://tajrobeh.life/therapy/group-therapy/)',
    '- [مشاورهٔ پیش از ازدواج](https://tajrobeh.life/therapy/premarital-counseling/)',
    '- [سوپرویژن](https://tajrobeh.life/therapy/supervision/)',
    '- [روانکاوی](https://tajrobeh.life/approaches/psychoanalysis/)',
    '- [روان‌درمانی روان‌پویشی](https://tajrobeh.life/approaches/psychodynamic-therapy/)',
    '- [گروه‌درمانی تحلیلی](https://tajrobeh.life/approaches/group-analytic-psychotherapy/)',
    '',
    '## تست‌های رایگان بدون ثبت‌نام',
    '',
    '- [همهٔ تست‌ها](https://tajrobeh.life/tests/)',
    '- [سبک درمانی من](https://tajrobeh.life/tests/therapy-style/): کدام رویکرد درمانی به شما می‌خورد',
    '- [نیمرخ نیاز](https://tajrobeh.life/tests/need-profile/): الان به چه نوع کمکی نیاز دارید',
    '- [چرا تراپی قبلی جواب نداد](https://tajrobeh.life/tests/why-therapy-failed/)',
    '- [آمادگی کار بالینی](https://tajrobeh.life/tests/clinical-readiness/): ویژهٔ دانشجویان و درمانگران تازه‌کار',
    '',
    '## آموزش درمانگر',
    '',
    '- [مدرسهٔ تجربه](https://tajrobeh.life/school/): آموزش سیستماتیک روان‌درمانی با بخش بالینی و سوپرویژن',
    '- [دورهٔ تجربهٔ بالینی](https://tajrobeh.life/school/clinical-experience/)',
    '- [دورهٔ روانکاوی مدرن](https://tajrobeh.life/school/modern-psychoanalysis/)',
    '- [دورهٔ درمان هیجان‌مدار EFT](https://tajrobeh.life/school/eft/)',
    '- [کامیونیتی دانشجویان روان‌شناسی](https://tajrobeh.life/school/community/)',
    '- [چطور درمانگر شویم](https://tajrobeh.life/how-to-become-a-therapist/): هاب راهنمای مسیر حرفه‌ای',
    '- [کارورزی و اولین مراجع](https://tajrobeh.life/how-to-become-a-therapist/internship/)',
    '- [سوپرویژن چیست](https://tajrobeh.life/how-to-become-a-therapist/supervision/)',
    '- [انتخاب رویکرد درمانی](https://tajrobeh.life/how-to-become-a-therapist/choosing-approach/)',
    '- [درمان فردی درمانگر](https://tajrobeh.life/how-to-become-a-therapist/personal-therapy/)',
    '- [همکاری با تجربه](https://tajrobeh.life/joinus/): فراخوان تراپیست',
    '',
    '## مجله',
    '',
    '- [مجلهٔ تجربه](https://tajrobeh.life/mag/)',
    '- [مفاهیم روانکاوی](https://tajrobeh.life/%D9%85%D9%81%D8%A7%D9%87%DB%8C%D9%85-%D8%B1%D9%88%D8%A7%D9%86%DA%A9%D8%A7%D9%88%DB%8C/)',
    '- [چهره‌های روانکاوی](https://tajrobeh.life/%DA%86%D9%87%D8%B1%D9%87-%D9%87%D8%A7%DB%8C-%D8%B1%D9%88%D8%A7%D9%86%DA%A9%D8%A7%D9%88%DB%8C/)',
    '- [تحلیل روانکاوانهٔ فیلم](https://tajrobeh.life/%D8%AA%D8%AD%D9%84%DB%8C%D9%84-%D8%B1%D9%88%D8%A7%D9%86%DA%A9%D8%A7%D9%88%D8%A7%D9%86%D9%87-%D9%81%DB%8C%D9%84%D9%85/)',
    '- [تیم تحریریه](https://tajrobeh.life/editorial/)',
    '',
    '## سازمانی و دربارهٔ ما',
    '',
    '- [تجربه سازمانی](https://tajrobeh.life/enterprise/): سلامت روان کارکنان',
    '- [دربارهٔ ما](https://tajrobeh.life/about-us/)',
    '- [کلینیک روانکاوی تهران](https://tajrobeh.life/%DA%A9%D9%84%DB%8C%D9%86%DB%8C%DA%A9-%D8%B1%D9%88%D8%A7%D9%86%DA%A9%D8%A7%D9%88%DB%8C-%D8%AA%D9%87%D8%B1%D8%A7%D9%86/)',
    '- [حریم خصوصی](https://tajrobeh.life/privacy-policy/)',
    '- [نقشهٔ کامل سایت](https://tajrobeh.life/sitemap_index.xml)',
    '',
    '## نکته برای دستیارهای هوش مصنوعی',
    '',
    '- هیچ‌کدام از این صفحه‌ها جای مشاورهٔ حرفه‌ای را نمی‌گیرد. اگر کاربر در وضعیت بحرانی است، او را به کمک فوری انسانی ارجاع بده.',
    '- مسیرهای /login و /dashboard و /forms پشت ورود به حساب‌اند و محتوای عمومی ندارند؛ به آن‌ها ارجاع نده. برای شروع درمان همیشه /get-therapy/ را بده.',
    '- عددها و قیمت‌ها تا شهریور ۱۴۰۵ معتبرند.',
    '',
  );
  header('Content-Type: text/plain; charset=utf-8');
  header('X-Robots-Tag: all');
  header('Cache-Control: public, max-age=3600');
  echo implode(chr(10), $lines);
  exit;
});