/**
 * Tajrobeh — مکث کوتاه v1 (tjmk) · ۷ مهر ۱۴۰۵
 * رفتار جعبهٔ «دو سؤال از همین مطلب، یک سؤال از خودتان» در مقاله‌های مجله.
 * سؤال‌ها داخل خود مقاله در بلوک .tjmk هستند؛ این اسنیپت فقط رفتار و رهگیری را می‌دهد. سبک در اسنیپت 504035 (tjmk).
 * پرسش آخر بات را با کد شروع معتبر باز می‌کند: self → mg-<id>-t · pro → mg-<id>-s · بقیه همان کد بلوک اصلی بات.
 * رویدادها: quiz_view · quiz_answer · quiz_reflect · quiz_bot_click
 */
add_action('wp_footer', function () {
    if (!is_singular('post')) { return; }
    echo <<<'TJQ'
<script id="tjmk-js">(function(){var R={self:['این تجربه ارزش شنیده شدن دارد. در بات تجربه با چند سؤال کوتاه می‌بینید چه نوع همراهی به کارتان می‌آید و اگر خواستید، جلسهٔ معارفهٔ رایگان را همان‌جا رزرو می‌کنید.','ادامه در بات تجربه','t'],learn:['در بات تجربه موضوع‌هایی را که دوست دارید انتخاب کنید تا مطلب‌های تازهٔ مجله را از دست ندهید.','انتخاب موضوع در بات تجربه',''],curious:['ممنون که تا اینجا خواندید. اگر خواستید، پیشنهادهای خواندنی مجله را در بات تجربه دنبال کنید.','بات تجربه',''],pro:['مسیر درمانگر شدن در مدرسهٔ تجربه با تحلیل فردی، سوپرویژن و کار بالینی ساخته شده است. در بات تجربه می‌توانید به کامیونیتی تجربه بپیوندید.','کامیونیتی تجربه در بات','s']};function ev(n,p){try{if(window.gtag){window.gtag('event',n,p);}if(window.dataLayer){window.dataLayer.push(Object.assign({event:n},p));}}catch(e){}}var boxes=document.querySelectorAll('.tjmk');[].forEach.call(boxes,function(box){var id=box.getAttribute('data-id')||'';var qs=[].slice.call(box.querySelectorAll('.tjmk-q'));var bar=box.querySelector('.tjmk-p i');var done=0;box.classList.add('tjmk-on');qs.forEach(function(q,i){if(i>0){q.classList.add('tjmk-wait');}});function step(){done++;if(bar){bar.style.width=Math.round(done/qs.length*100)+'%';}var nx=qs[done];if(nx){nx.classList.remove('tjmk-wait');}}if('IntersectionObserver' in window){var io=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){ev('quiz_view',{post_id:id,page_path:location.pathname});io.disconnect();}});},{threshold:0.4});io.observe(box);}qs.forEach(function(q,i){var bs=[].slice.call(q.querySelectorAll('.tjmk-o button'));bs.forEach(function(b,j){b.addEventListener('click',function(){if(q.getAttribute('data-done')){return;}q.setAttribute('data-done','1');bs.forEach(function(x){x.disabled=true;});if(q.classList.contains('tjmk-r')){b.classList.add('is-ok');var k=b.getAttribute('data-k')||'curious';var r=R[k]||R.curious;var end=q.querySelector('.tjmk-end');end.querySelector('.tjmk-m').textContent=r[0];var a=end.querySelector('.tjmk-bot');a.textContent=r[1];var st='';if(r[2]){st='mg-'+id+'-'+r[2];}else{var m=document.querySelector('.tjbot a[href*="start=mg-"]');var mm=m?m.getAttribute('href').match(/start=(mg-[0-9]+-[a-z])/):null;st=mm?mm[1]:'mg-'+id+'-t';}a.href='https://t.me/tajrobehlife_bot?start='+st;a.setAttribute('data-start',st);end.hidden=false;ev('quiz_reflect',{post_id:id,kind:k,page_path:location.pathname});a.addEventListener('click',function(){ev('quiz_bot_click',{post_id:id,kind:k,start_param:st,page_path:location.pathname});});}else{var ok=parseInt(q.getAttribute('data-ok'),10);var good=(j===ok);if(bs[ok]){bs[ok].classList.add('is-ok');}if(!good){b.classList.add('is-no');}var e=q.querySelector('.tjmk-e');if(e){e.textContent=(good?'درست است. ':'نه دقیقاً. ')+e.textContent;e.hidden=false;}ev('quiz_answer',{post_id:id,q:i+1,correct:good?1:0,page_path:location.pathname});}step();});});});});})();</script>
TJQ;
}, 30);
